name: Hello, World!
on: push

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - run: |
          mkdir data
          echo "Hello" > data/hello.txt
      - uses: actions/upload-artifact@v2
        with:
          name: data
          path: data
